# Goose Configuration for Local DeepSeek-R1 INT4-AWQ OpenVINO
# Place this in ~/.config/goose/config.yaml ONLY if you don't have existing config
# See installer instructions for safe configuration

# Local DeepSeek-R1 INT4-AWQ OpenVINO Configuration  
GOOSE_MODEL: deepseek-r1-openvino
GOOSE_PROVIDER: openai  # Use OpenAI-compatible API
GOOSE_API_BASE: http://localhost:8000/v1  # Local server endpoint
GOOSE_API_KEY: local-key  # Dummy key for local server
GOOSE_MODE: smart_approve
GOOSE_CLI_MIN_PRIORITY: 0.8

# System prompt optimized for DeepSeek-R1's thinking capabilities
GOOSE_SYSTEM_PROMPT: |
  You are DeepSeek-R1, an advanced reasoning model. Provide clear, well-reasoned code and explanations.
  Think through problems step by step and focus on practical, efficient solutions.

# Extensions configuration
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin

# Performance and reliability settings
request_timeout: 60  # Extended timeout for local inference
max_tokens: 150      # Limit response length for faster generation
temperature: 0.7     # Moderate creativity for coding tasks

# Optional: Ollama fallback if you have it installed
# OLLAMA_HOST: localhost
# OLLAMA_MODEL: qwen3:8b
