# Goose Configuration for Local NPGlue (Qwen3 + OpenVINO)
# Place this in ~/.config/goose/config.yaml ONLY if you don't have existing config
# See installer instructions for safe configuration

# IMPORTANT: Set this environment variable before using Goose:
# export OPENAI_API_KEY="sk-1234567890abcdef1234567890abcdef1234567890abcdef1234"
# (Goose requires this in keychain/env, not in config file)

# Local Qwen3 OpenVINO Configuration via NPGlue
GOOSE_PROVIDER: openai  # Use OpenAI-compatible API
GOOSE_MODEL: qwen3  # NPGlue serves Qwen3 models
GOOSE_API_BASE: http://localhost:11434/v1  # NPGlue server endpoint

# System prompt for development assistant
GOOSE_SYSTEM_PROMPT: |
  You are a helpful AI development assistant. Provide clear, practical solutions and direct answers.
  Focus on actionable code and efficient problem-solving.

# Performance settings
GOOSE_MODE: approve
GOOSE_CLI_MIN_PRIORITY: 0.8

# Extensions configuration
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
