# Goose Configuration for Local NPGlue (Qwen3 + OpenVINO)
# Place this in ~/.config/goose/config.yaml ONLY if you don't have existing config
# See installer instructions for safe configuration

# Local Qwen3 OpenVINO Configuration via NPGlue
provider: openai  # Use OpenAI-compatible API
model: qwen3  # NPGlue serves Qwen3 models
api_base: http://localhost:11434/v1  # NPGlue server endpoint
api_key: local-key  # Dummy key for local server

# System prompt for development assistant
system_prompt: |
  You are a helpful AI development assistant. Provide clear, practical solutions and direct answers.
  Focus on actionable code and efficient problem-solving.

# Extensions configuration
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin

# Performance and reliability settings
request_timeout: 60  # Extended timeout for local inference
max_tokens: 1000     # Allow longer responses (NPGlue supports up to 4096)
temperature: 0.7     # Moderate creativity for coding tasks
